name: Waka Readme

on:
  schedule:
    - cron: '35 19 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # 时间线
          SHOW_PROFILE_VIEWS : False
          SHOW_LOC_CHART : False
          SHOW_LINES_OF_CODE : True
          SHOW_TOTAL_CODE_TIME : True
          SHOW_COMMIT : True
          SHOW_DAYS_OF_WEEK : True
          SHOW_PROJECTS : True
